name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Runs when you push to main
    paths: 
      - '**/*.js'
      - '**/*.vue'
      - 'package.json'
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows action to create gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # insrall node.js
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # install dependencies and build
      - name: Install & build
        run: |
          npm install
          npm run build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist # Deploys the ENTIRE repo
