name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"] # Runs when you push to main

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows action to create gh-pages branch

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Deploys the ENTIRE repo
